sudo: required

language: generic

services:
  - docker

addons:
    apt:
        sources:
            - sourceline: deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main
              key_url: https://packages.microsoft.com/keys/microsoft.asc

        packages:
            - libunwind8
            - azure-functions-core-tools

# before_install:
# - docker pull microsoft/azure-functions-python3.6
# - docker run -it -v /home/travis/build/asavaritayal/pythonfunctionsandtravis:/home/site/wwwroot:rw microsoft/azure-functions-python3.6  /bin/sh -c "cd /home/site/wwwroot; python -m venv --copies worker_venv; source worker_venv/bin/activate; pip install -r requirements.txt; apt-get update; apt-get install zip -y; zip --symlinks -r /home/site/wwwroot/app.zip .;"

# - echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ wheezy main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
# - curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
# - sudo apt-get install apt-transport-https
# - sudo apt-get update && sudo apt-get install azure-cli

script:
- ls
- func

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: l53Y4Ut7d35fcu21hXK0EyMdp8gJnHToHam0oAxxtN6eXxxtZhGIt6c9e/xr4ASE/JlLhf+bu6bT+bS7MlFjxi7vh678wANS4gRwE9u7nXK8IYAIhBVLqpGcxLi63j5EhYJnS+zOwj5u+adYyUPmE3XZZW5jqde3amtw5Z2knMtKqc6fIVEYs157mwQBRNMzT7K4oV2k87g3cEiGpnz2ixKtKTZIm3YmdI1CzxlotIrM9SZF0jFH8Egxmcs6L/jzIch2sVpOtM354OwgodtviTCo+xeaLRPqPcHxMxTG3MVIem3VpDfaGKRHZ6+ZSlj0w3MA3dV8txHJpINxg0ajHhW/ibeKXdeXKAkM5K1etwZuf3wSWGRaZIpUXpwFnwcEFZW3P+zU10ypQ4D7IjD1ovcMIQd5ALb8A/XPcK7OOflIxJo85PBztd1v8GWToPe7FCDySFYEcfAuHl7zuEbgeTDoO3eIvIc2BTHzVbWhx48fxtEqexsm+wDZgts7H1juU9ntRK38oruBoQwzZXgOx89DvgzWBXsbDKnM+E3j56Y/JBlLMSQ8TdpYHYrqYeXF1GCklEryNIFKGtPGKESmDUOEp9445T3+SpzqIysaSoj6iMSEcfYU1uZxWQB+rXKEXZF4zH7Z4jbdaCUQZahKjQgQzFcVUZOkTkashPaGeoo=
  file: app.zip
  on:
    repo: asavaritayal/pythonfunctionsandtravis