sudo: required

language: python

services:
  - docker

before_install:
- docker pull microsoft/azure-functions-python3.6
- docker run -d microsoft/azure-functions-python3.6
- docker ps -a

script:
- python --version