dist: trusty
sudo: false

branches:
    only:
        - master

language: python
python:
    - 3.6
virtualenv:
  system_site_packages: true
  
cache:
    pip: true

script:
  - python --version
  - pip install requests
  - pwd
  - ls