dist: trusty
sudo: false

branches:
    only:
        - master

language: python
python:
  - 3.6

install:
  - pip install virtualenv

script:
  - python --version
  - python3.6 -m venv worker_env
  - source worker_env/bin/activate
  - pip install requests
  - pwd
  - ls