sudo: required

language: python

services:
  - docker

before_install:
- docker pull microsoft/azure-functions-python3.6
- docker run -d microsoft/azure-functions-python3.6  /bin/sh -c "python --version;"
- docker ps -a

script:
- ls