dist: trusty
sudo: false

branches:
    only:
        - master

language: python
python:
    - 3.6

cache:
    pip: true

script:
    - python --version
    - pip install --upgrade pip
    - pip install virtualenv
    - python3.6 -m venv worker_env
    - source worker_env/bin/activate
    - pip install requests

