sudo: required

language: generic

services:
  - docker

before_install:
- pwd
- docker pull microsoft/azure-functions-python3.6
- docker run -v /home/travis/build/asavaritayal/pythonfunctionsandtravis:/home/site/wwwroot:rw microsoft/azure-functions-python3.6  /bin/sh -c "mkdir test"

script:
- ls