dist: trusty
sudo: false

branches:
    only:
        - master

language: python
python:
  - 3.6

install:
  - pip install virtualenv

script:
  - python3.6 -m venv worker_env
  - source worker_env/bin/activate
  - python --version
  - pip install -r requirements.txt
  - pwd
  - cd worker_env
  - ls

# deploy:
#   provider: releases
#   api_key: "GITHUB OAUTH TOKEN"
#   file: "FILE TO UPLOAD"
#   skip_cleanup: true