dist: trusty
sudo: false

branches:
    only:
        - master

language: python
python:
  - 3.6

install:
  - pip3 install virtualenv

script:
  - python3.6 -m venv --copies worker_env
  - source worker_env/bin/activate
  - pip install setuptools
  - pip install wheel
  - pip install -r requirements.txt
  - pwd
  - cd worker_env
  - ls